[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--doctest-modules --doctest-continue-on-failure"
doctest_optionflags = "NORMALIZE_WHITESPACE"

[tool.ruff]
line-length = 120
extend-include = [
    "I",  # isort
    "UP", # pyupgrade
]
lint.fixable = ["E", "F", "I"]
